/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6e30b7929fd23bf898e51313903b634f)
interface __BaseEnv_Env {
	SANITY_PROJECT_ID: "kqwm7tyx";
	SANITY_DATASET: "production";
	SANITY_API_VERSION: "2025-02-19";
	SANITY_READ_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SANITY_PROJECT_ID" | "SANITY_DATASET" | "SANITY_API_VERSION" | "SANITY_READ_TOKEN">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}