/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type HeroTile = {
  _type: 'heroTile';
  target?: 'exhibitions' | 'valueGenerator' | 'experientialEducation' | 'custom';
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  customLink?: NamedLink;
};

export type MapPoint = {
  _type: 'mapPoint';
  title?: string;
  location?: Geopoint;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  link?: NamedLink;
};

export type Person = {
  _type: 'person';
  name?: string;
  position?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type GalleryImage = {
  _type: 'galleryImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  photographer?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  name?: string;
  url?: string;
  icon?: string;
};

export type RoleWithPeople = {
  _type: 'roleWithPeople';
  role?: string;
  people?: string;
};

export type MaterialFile = {
  _type: 'materialFile';
  title?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    media?: unknown;
    _type: 'file';
  };
};

export type RichTextFull = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal';
  listItem?: 'bullet';
  markDefs?: Array<{
    href?: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type RichTextBasic = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal';
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type MaterialsBlock = {
  _type: 'materialsBlock';
  materials?: Array<
    {
      _key: string;
    } & MaterialFile
  >;
};

export type TileBlock = {
  _type: 'tileBlock';
  content?: Array<
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & HeadingBlock)
    | ({
        _key: string;
      } & DecorativeImage)
    | ({
        _key: string;
      } & MaterialsBlock)
  >;
};

export type DecorativeImage = {
  _type: 'decorativeImage';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  alt?: string;
};

export type HeadingBlock = {
  _type: 'headingBlock';
  text?: string;
  level?: 'h2' | 'h3';
};

export type TextBlock = {
  _type: 'textBlock';
  content?: RichTextFull;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & TextBlock)
  | ({
      _key: string;
    } & HeadingBlock)
  | ({
      _key: string;
    } & DecorativeImage)
  | ({
      _key: string;
    } & TileBlock)
  | ({
      _key: string;
    } & MaterialsBlock)
>;

export type ValueGenerator = {
  _id: string;
  _type: 'valueGenerator';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cover?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'coverImage';
  };
  content?: PageBuilder;
  mapPoints?: Array<
    {
      _key: string;
    } & MapPoint
  >;
};

export type ExperientialEducation = {
  _id: string;
  _type: 'experientialEducation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cover?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'coverImage';
  };
  content?: PageBuilder;
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cover?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'coverImage';
  };
  phone?: string;
  email?: string;
  address?: RichTextBasic;
  administrativeInfo?: RichTextBasic;
  people?: Array<
    {
      _key: string;
    } & Person
  >;
};

export type Exhibition = {
  _id: string;
  _type: 'exhibition';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  canOpenDetail?: boolean;
  place?: string;
  openingDate?: string;
  startDate?: string;
  endDate?: string;
  roles?: Array<
    {
      _key: string;
    } & RoleWithPeople
  >;
  cover?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'coverImage';
  };
  gallery?: Array<
    {
      _key: string;
    } & GalleryImage
  >;
  abstract?: RichTextBasic;
  materials?: Array<
    {
      _key: string;
    } & MaterialFile
  >;
  links?: Array<
    {
      _key: string;
    } & NamedLink
  >;
  contributors?: Array<
    {
      _key: string;
    } & RoleWithPeople
  >;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cover?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'coverImage';
  };
  heroTiles?: Array<
    {
      _key: string;
    } & HeroTile
  >;
  introExcerpt?: RichTextBasic;
  introRest?: RichTextBasic;
};

export type CoverImage = {
  _type: 'coverImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  donateLink?: NamedLink;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  partners?: RichTextBasic;
};

export type NamedLink = {
  _type: 'namedLink';
  label?: string;
  href?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | HeroTile
  | MapPoint
  | Person
  | GalleryImage
  | SocialLink
  | RoleWithPeople
  | MaterialFile
  | RichTextFull
  | RichTextBasic
  | MaterialsBlock
  | TileBlock
  | DecorativeImage
  | HeadingBlock
  | TextBlock
  | PageBuilder
  | ValueGenerator
  | ExperientialEducation
  | ContactPage
  | Exhibition
  | HomePage
  | CoverImage
  | SiteSettings
  | NamedLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    donateLink,    socialLinks[]{ _key, name, url, icon },    partners  }
export type SETTINGS_QUERYResult =
  | {
      donateLink: null;
      socialLinks: null;
      partners: null;
    }
  | {
      donateLink: NamedLink | null;
      socialLinks: Array<{
        _key: string;
        name: string | null;
        url: string | null;
        icon: string | null;
      }> | null;
      partners: RichTextBasic | null;
    }
  | null;
// Variable: HOME_QUERY
// Query: *[_id == "homePage"][0]{    cover{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },    heroTiles[]{      _key,      target,      title,      image{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },      customLink    },    introExcerpt,    introRest  }
export type HOME_QUERYResult =
  | {
      cover: null;
      heroTiles: null;
      introExcerpt: null;
      introRest: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      heroTiles: null;
      introExcerpt: null;
      introRest: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      heroTiles: Array<{
        _key: string;
        target: 'custom' | 'exhibitions' | 'experientialEducation' | 'valueGenerator' | null;
        title: string | null;
        image: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          alt: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        customLink: NamedLink | null;
      }> | null;
      introExcerpt: RichTextBasic | null;
      introRest: RichTextBasic | null;
    }
  | null;
// Variable: EXHIBITIONS_QUERY
// Query: *[_type == "exhibition"] | order(endDate desc){    _id,    title,    "slug": slug.current,    place,    openingDate,    startDate,    endDate,    canOpenDetail,    cover{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop }  }
export type EXHIBITIONS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  place: string | null;
  openingDate: string | null;
  startDate: string | null;
  endDate: string | null;
  canOpenDetail: boolean | null;
  cover: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;
// Variable: EXHIBITION_SLUGS_QUERY
// Query: *[_type == "exhibition" && defined(slug.current) && canOpenDetail == true]{    "slug": slug.current  }
export type EXHIBITION_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: EXHIBITION_QUERY
// Query: *[_type == "exhibition" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    place,    openingDate,    startDate,    endDate,    canOpenDetail,    roles[]{ _key, role, people },    cover{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },    gallery[]{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop, photographer },    abstract,    materials[]{   _key,  title,  "url": file.asset->url,  "extension": file.asset->extension,  "size": file.asset->size },    links[]{ _key, label, href },    contributors[]{ _key, role, people }  }
export type EXHIBITION_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  place: string | null;
  openingDate: string | null;
  startDate: string | null;
  endDate: string | null;
  canOpenDetail: boolean | null;
  roles: Array<{
    _key: string;
    role: string | null;
    people: string | null;
  }> | null;
  cover: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    photographer: string | null;
  }> | null;
  abstract: RichTextBasic | null;
  materials: Array<{
    _key: string;
    title: string | null;
    url: string | null;
    extension: string | null;
    size: number | null;
  }> | null;
  links: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
  contributors: Array<{
    _key: string;
    role: string | null;
    people: string | null;
  }> | null;
} | null;
// Variable: CONTACT_QUERY
// Query: *[_id == "contactPage"][0]{    cover{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },    phone,    email,    address,    administrativeInfo,    people[]{      _key,      name,      position,      image{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop }    }  }
export type CONTACT_QUERYResult =
  | {
      cover: null;
      phone: null;
      email: null;
      address: null;
      administrativeInfo: null;
      people: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      phone: null;
      email: null;
      address: null;
      administrativeInfo: null;
      people: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      phone: string | null;
      email: string | null;
      address: RichTextBasic | null;
      administrativeInfo: RichTextBasic | null;
      people: Array<{
        _key: string;
        name: string | null;
        position: string | null;
        image: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          alt: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
      }> | null;
    }
  | null;
// Variable: EXPERIENTIAL_EDUCATION_QUERY
// Query: *[_id == "experientialEducation"][0]{    cover{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },      content[]{    _key,    _type,    _type == "textBlock" => { content },    _type == "headingBlock" => { text, level },    _type == "decorativeImage" => { image{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop }, alt },    _type == "materialsBlock" => { materials[]{   _key,  title,  "url": file.asset->url,  "extension": file.asset->extension,  "size": file.asset->size } },    _type == "tileBlock" => {      content[]{        _key,        _type,        _type == "textBlock" => { content },        _type == "headingBlock" => { text, level },        _type == "decorativeImage" => { image{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop }, alt },        _type == "materialsBlock" => { materials[]{   _key,  title,  "url": file.asset->url,  "extension": file.asset->extension,  "size": file.asset->size } },      }    },  }  }
export type EXPERIENTIAL_EDUCATION_QUERYResult =
  | {
      cover: null;
      content: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      content: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      content: Array<
        | {
            _key: string;
            _type: 'decorativeImage';
            image: {
              asset: {
                _id: string;
                url: string | null;
                metadata: {
                  lqip: string | null;
                  dimensions: SanityImageDimensions | null;
                } | null;
              } | null;
              alt: null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
            alt: string | null;
          }
        | {
            _key: string;
            _type: 'headingBlock';
            text: string | null;
            level: 'h2' | 'h3' | null;
          }
        | {
            _key: string;
            _type: 'materialsBlock';
            materials: Array<{
              _key: string;
              title: string | null;
              url: string | null;
              extension: string | null;
              size: number | null;
            }> | null;
          }
        | {
            _key: string;
            _type: 'textBlock';
            content: RichTextFull | null;
          }
        | {
            _key: string;
            _type: 'tileBlock';
            content: Array<
              | {
                  _key: string;
                  _type: 'decorativeImage';
                  image: {
                    asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                        lqip: string | null;
                        dimensions: SanityImageDimensions | null;
                      } | null;
                    } | null;
                    alt: null;
                    hotspot: SanityImageHotspot | null;
                    crop: SanityImageCrop | null;
                  } | null;
                  alt: string | null;
                }
              | {
                  _key: string;
                  _type: 'headingBlock';
                  text: string | null;
                  level: 'h2' | 'h3' | null;
                }
              | {
                  _key: string;
                  _type: 'materialsBlock';
                  materials: Array<{
                    _key: string;
                    title: string | null;
                    url: string | null;
                    extension: string | null;
                    size: number | null;
                  }> | null;
                }
              | {
                  _key: string;
                  _type: 'textBlock';
                  content: RichTextFull | null;
                }
            > | null;
          }
      > | null;
    }
  | null;
// Variable: VALUE_GENERATOR_QUERY
// Query: *[_id == "valueGenerator"][0]{    cover{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },      content[]{    _key,    _type,    _type == "textBlock" => { content },    _type == "headingBlock" => { text, level },    _type == "decorativeImage" => { image{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop }, alt },    _type == "materialsBlock" => { materials[]{   _key,  title,  "url": file.asset->url,  "extension": file.asset->extension,  "size": file.asset->size } },    _type == "tileBlock" => {      content[]{        _key,        _type,        _type == "textBlock" => { content },        _type == "headingBlock" => { text, level },        _type == "decorativeImage" => { image{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop }, alt },        _type == "materialsBlock" => { materials[]{   _key,  title,  "url": file.asset->url,  "extension": file.asset->extension,  "size": file.asset->size } },      }    },  },    mapPoints[]{      _key,      title,      location,      image{   asset->{ _id, url, metadata { lqip, dimensions } },  alt,  hotspot,  crop },      text,      link    }  }
export type VALUE_GENERATOR_QUERYResult =
  | {
      cover: null;
      content: null;
      mapPoints: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      content: null;
      mapPoints: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      content: Array<
        | {
            _key: string;
            _type: 'decorativeImage';
            image: {
              asset: {
                _id: string;
                url: string | null;
                metadata: {
                  lqip: string | null;
                  dimensions: SanityImageDimensions | null;
                } | null;
              } | null;
              alt: null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
            alt: string | null;
          }
        | {
            _key: string;
            _type: 'headingBlock';
            text: string | null;
            level: 'h2' | 'h3' | null;
          }
        | {
            _key: string;
            _type: 'materialsBlock';
            materials: Array<{
              _key: string;
              title: string | null;
              url: string | null;
              extension: string | null;
              size: number | null;
            }> | null;
          }
        | {
            _key: string;
            _type: 'textBlock';
            content: RichTextFull | null;
          }
        | {
            _key: string;
            _type: 'tileBlock';
            content: Array<
              | {
                  _key: string;
                  _type: 'decorativeImage';
                  image: {
                    asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                        lqip: string | null;
                        dimensions: SanityImageDimensions | null;
                      } | null;
                    } | null;
                    alt: null;
                    hotspot: SanityImageHotspot | null;
                    crop: SanityImageCrop | null;
                  } | null;
                  alt: string | null;
                }
              | {
                  _key: string;
                  _type: 'headingBlock';
                  text: string | null;
                  level: 'h2' | 'h3' | null;
                }
              | {
                  _key: string;
                  _type: 'materialsBlock';
                  materials: Array<{
                    _key: string;
                    title: string | null;
                    url: string | null;
                    extension: string | null;
                    size: number | null;
                  }> | null;
                }
              | {
                  _key: string;
                  _type: 'textBlock';
                  content: RichTextFull | null;
                }
            > | null;
          }
      > | null;
      mapPoints: null;
    }
  | {
      cover: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      content: Array<
        | {
            _key: string;
            _type: 'decorativeImage';
            image: {
              asset: {
                _id: string;
                url: string | null;
                metadata: {
                  lqip: string | null;
                  dimensions: SanityImageDimensions | null;
                } | null;
              } | null;
              alt: null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
            } | null;
            alt: string | null;
          }
        | {
            _key: string;
            _type: 'headingBlock';
            text: string | null;
            level: 'h2' | 'h3' | null;
          }
        | {
            _key: string;
            _type: 'materialsBlock';
            materials: Array<{
              _key: string;
              title: string | null;
              url: string | null;
              extension: string | null;
              size: number | null;
            }> | null;
          }
        | {
            _key: string;
            _type: 'textBlock';
            content: RichTextFull | null;
          }
        | {
            _key: string;
            _type: 'tileBlock';
            content: Array<
              | {
                  _key: string;
                  _type: 'decorativeImage';
                  image: {
                    asset: {
                      _id: string;
                      url: string | null;
                      metadata: {
                        lqip: string | null;
                        dimensions: SanityImageDimensions | null;
                      } | null;
                    } | null;
                    alt: null;
                    hotspot: SanityImageHotspot | null;
                    crop: SanityImageCrop | null;
                  } | null;
                  alt: string | null;
                }
              | {
                  _key: string;
                  _type: 'headingBlock';
                  text: string | null;
                  level: 'h2' | 'h3' | null;
                }
              | {
                  _key: string;
                  _type: 'materialsBlock';
                  materials: Array<{
                    _key: string;
                    title: string | null;
                    url: string | null;
                    extension: string | null;
                    size: number | null;
                  }> | null;
                }
              | {
                  _key: string;
                  _type: 'textBlock';
                  content: RichTextFull | null;
                }
            > | null;
          }
      > | null;
      mapPoints: Array<{
        _key: string;
        title: string | null;
        location: Geopoint | null;
        image: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          alt: null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        } | null;
        text: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'normal';
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }> | null;
        link: NamedLink | null;
      }> | null;
    }
  | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    donateLink,\n    socialLinks[]{ _key, name, url, icon },\n    partners\n  }\n': SETTINGS_QUERYResult;
    '\n  *[_id == "homePage"][0]{\n    cover{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n    heroTiles[]{\n      _key,\n      target,\n      title,\n      image{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n      customLink\n    },\n    introExcerpt,\n    introRest\n  }\n': HOME_QUERYResult;
    '\n  *[_type == "exhibition"] | order(endDate desc){\n    _id,\n    title,\n    "slug": slug.current,\n    place,\n    openingDate,\n    startDate,\n    endDate,\n    canOpenDetail,\n    cover{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }\n  }\n': EXHIBITIONS_QUERYResult;
    '\n  *[_type == "exhibition" && defined(slug.current) && canOpenDetail == true]{\n    "slug": slug.current\n  }\n': EXHIBITION_SLUGS_QUERYResult;
    '\n  *[_type == "exhibition" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    place,\n    openingDate,\n    startDate,\n    endDate,\n    canOpenDetail,\n    roles[]{ _key, role, people },\n    cover{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n    gallery[]{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n, photographer },\n    abstract,\n    materials[]{ \n  _key,\n  title,\n  "url": file.asset->url,\n  "extension": file.asset->extension,\n  "size": file.asset->size\n },\n    links[]{ _key, label, href },\n    contributors[]{ _key, role, people }\n  }\n': EXHIBITION_QUERYResult;
    '\n  *[_id == "contactPage"][0]{\n    cover{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n    phone,\n    email,\n    address,\n    administrativeInfo,\n    people[]{\n      _key,\n      name,\n      position,\n      image{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }\n    }\n  }\n': CONTACT_QUERYResult;
    '\n  *[_id == "experientialEducation"][0]{\n    cover{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n    \n  content[]{\n    _key,\n    _type,\n    _type == "textBlock" => { content },\n    _type == "headingBlock" => { text, level },\n    _type == "decorativeImage" => { image{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }, alt },\n    _type == "materialsBlock" => { materials[]{ \n  _key,\n  title,\n  "url": file.asset->url,\n  "extension": file.asset->extension,\n  "size": file.asset->size\n } },\n    _type == "tileBlock" => {\n      content[]{\n        _key,\n        _type,\n        _type == "textBlock" => { content },\n        _type == "headingBlock" => { text, level },\n        _type == "decorativeImage" => { image{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }, alt },\n        _type == "materialsBlock" => { materials[]{ \n  _key,\n  title,\n  "url": file.asset->url,\n  "extension": file.asset->extension,\n  "size": file.asset->size\n } },\n      }\n    },\n  }\n\n  }\n': EXPERIENTIAL_EDUCATION_QUERYResult;
    '\n  *[_id == "valueGenerator"][0]{\n    cover{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n    \n  content[]{\n    _key,\n    _type,\n    _type == "textBlock" => { content },\n    _type == "headingBlock" => { text, level },\n    _type == "decorativeImage" => { image{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }, alt },\n    _type == "materialsBlock" => { materials[]{ \n  _key,\n  title,\n  "url": file.asset->url,\n  "extension": file.asset->extension,\n  "size": file.asset->size\n } },\n    _type == "tileBlock" => {\n      content[]{\n        _key,\n        _type,\n        _type == "textBlock" => { content },\n        _type == "headingBlock" => { text, level },\n        _type == "decorativeImage" => { image{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n }, alt },\n        _type == "materialsBlock" => { materials[]{ \n  _key,\n  title,\n  "url": file.asset->url,\n  "extension": file.asset->extension,\n  "size": file.asset->size\n } },\n      }\n    },\n  }\n,\n    mapPoints[]{\n      _key,\n      title,\n      location,\n      image{ \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  alt,\n  hotspot,\n  crop\n },\n      text,\n      link\n    }\n  }\n': VALUE_GENERATOR_QUERYResult;
  }
}
